stages:
  - build
  - test

.build:
  image: ruby:3.1.2
  before_script:
    - gem install bundler --no-document
    - bundle install --jobs $(nproc) "${FLAGS[@]}" --path=vendor

.db:
  extends: .build
  services:
    - postgres:12.0
  variables:
    POSTGRES_USER: dogli
    POSTGRES_PASSWORD: kapil
    DB_USERNAME: dogli
    DB_PASSWORD: kapil
    DB_HOST: postgres
    RAILS_ENV: test
    DISABLE_SPRING: 1
    BUNDLE_PATH: vendor/bundle
  before_script:
    - export APT_CACHE_DIR=`pwd`/apt-cache && mkdir -pv $APT_CACHE_DIR
    - apt update -qq && apt -o dir::cache::archives="$APT_CACHE_DIR" install -yqq nodejs
    - gem install bundler --no-document
    - bundle install --jobs $(nproc) "${FLAGS[@]}" --path=vendor
    - bundle exec rails db:create db:schema:load --trace

rubocop:
  extends: .build
  stage: build
  script:
    - bundle exec rubocop

rspec:
  extends: .db
  stage: test
  script:
    - bundle exec rspec --profile 10 --format progress

test:bundle_audit:
  extends: .base
  allow_failure: true
  script:
    - bundle exec bundle audit check --update
